### ISSUE TITLE
data-textfit-min does not work

### ISSUE THREAD

**Issue by arachnidus** [kthornbloom/textfit#1]
Hi,
I want to use text-fit with a minimum fontsize but it don't work. The minimum font-size is not set
The same as on your example with index.html.

**Comment by kthornbloom** [comment]
Thanks, I had an error in the documentation. Set the min (and max) font sizes using just numerical values. `data-textfit-min="40"` **NOT** `data-textfit-min="40px"`

**Comment by arachnidus** [comment]
Hi Kevin,

 

Thanks for your reply, I had already found it by testing and looking in the code.

 

Kind regards

 

Hans Stad
